export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "France",
  "Germany",
  "Italy",
  "Spain",
  "Switzerland",
  "United Arab Emirates",
  "Singapore",
  "Japan",
  "Australia",
  "Canada",
  "Brazil",
  "India",
  "China",
  "South Korea",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Greece",
  "Portugal",
  "Mexico",
  "South Africa",
  "Qatar",
  "Saudi Arabia",
  "Indonesia",
  "Thailand",
  "Maldives",
].sort();
